//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace O_ComTool_Pro {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class app : global::System.Configuration.ApplicationSettingsBase {
        
        private static app defaultInstance = ((app)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new app())));
        
        public static app Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string cmbBaudRate {
            get {
                return ((string)(this["cmbBaudRate"]));
            }
            set {
                this["cmbBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public short cmbDataBitIndex {
            get {
                return ((short)(this["cmbDataBitIndex"]));
            }
            set {
                this["cmbDataBitIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short cmbParityBitIndex {
            get {
                return ((short)(this["cmbParityBitIndex"]));
            }
            set {
                this["cmbParityBitIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short cmbStopBitIndex {
            get {
                return ((short)(this["cmbStopBitIndex"]));
            }
            set {
                this["cmbStopBitIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short cmbFlowCtrlIndex {
            get {
                return ((short)(this["cmbFlowCtrlIndex"]));
            }
            set {
                this["cmbFlowCtrlIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool receEncodeAscii {
            get {
                return ((bool)(this["receEncodeAscii"]));
            }
            set {
                this["receEncodeAscii"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sendEncodeAscii {
            get {
                return ((bool)(this["sendEncodeAscii"]));
            }
            set {
                this["sendEncodeAscii"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoLine {
            get {
                return ((bool)(this["chkAutoLine"]));
            }
            set {
                this["chkAutoLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkShowTime {
            get {
                return ((bool)(this["chkShowTime"]));
            }
            set {
                this["chkShowTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoReply {
            get {
                return ((bool)(this["chkAutoReply"]));
            }
            set {
                this["chkAutoReply"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int AutoReplyDelay {
            get {
                return ((int)(this["AutoReplyDelay"]));
            }
            set {
                this["AutoReplyDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAutoCount {
            get {
                return ((bool)(this["chkAutoCount"]));
            }
            set {
                this["chkAutoCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAppendNewLine {
            get {
                return ((bool)(this["chkAppendNewLine"]));
            }
            set {
                this["chkAppendNewLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkRepeatSend {
            get {
                return ((bool)(this["chkRepeatSend"]));
            }
            set {
                this["chkRepeatSend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int RepeatInterval {
            get {
                return ((int)(this["RepeatInterval"]));
            }
            set {
                this["RepeatInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.ifreehub.com")]
        public string GeneralSendData {
            get {
                return ((string)(this["GeneralSendData"]));
            }
            set {
                this["GeneralSendData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoadFilePath {
            get {
                return ((string)(this["LoadFilePath"]));
            }
            set {
                this["LoadFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinToTray {
            get {
                return ((bool)(this["MinToTray"]));
            }
            set {
                this["MinToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseToTray {
            get {
                return ((bool)(this["CloseToTray"]));
            }
            set {
                this["CloseToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2018-11-21 23:22:00")]
        public string LastCheckTime {
            get {
                return ((string)(this["LastCheckTime"]));
            }
            set {
                this["LastCheckTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("39, 40, 34")]
        public global::System.Drawing.Color ReceBackColor1 {
            get {
                return ((global::System.Drawing.Color)(this["ReceBackColor1"]));
            }
            set {
                this["ReceBackColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("248, 248, 242")]
        public global::System.Drawing.Color ReceForeColor1 {
            get {
                return ((global::System.Drawing.Color)(this["ReceForeColor1"]));
            }
            set {
                this["ReceForeColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("39, 40, 34")]
        public global::System.Drawing.Color SendBackColor1 {
            get {
                return ((global::System.Drawing.Color)(this["SendBackColor1"]));
            }
            set {
                this["SendBackColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("248, 248, 242")]
        public global::System.Drawing.Color SendForeColor1 {
            get {
                return ((global::System.Drawing.Color)(this["SendForeColor1"]));
            }
            set {
                this["SendForeColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas, 10.5pt")]
        public global::System.Drawing.Font ReceFont1 {
            get {
                return ((global::System.Drawing.Font)(this["ReceFont1"]));
            }
            set {
                this["ReceFont1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas, 10.5pt")]
        public global::System.Drawing.Font SendFont1 {
            get {
                return ((global::System.Drawing.Font)(this["SendFont1"]));
            }
            set {
                this["SendFont1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public short QuickSendCount {
            get {
                return ((short)(this["QuickSendCount"]));
            }
            set {
                this["QuickSendCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Title1</string>\r\n  <string>Title2</string>\r\n  <string>Title3</string>\r\n</A" +
            "rrayOfString>")]
        public global::System.Collections.Specialized.StringCollection QuickSendTitle {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["QuickSendTitle"]));
            }
            set {
                this["QuickSendTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Data1</string>\r\n  <string>Data2</string>\r\n  <string>Data3</string>\r\n</Arra" +
            "yOfString>")]
        public global::System.Collections.Specialized.StringCollection QuickSendData {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["QuickSendData"]));
            }
            set {
                this["QuickSendData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SkipVersion {
            get {
                return ((string)(this["SkipVersion"]));
            }
            set {
                this["SkipVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QuitConfirm {
            get {
                return ((bool)(this["QuitConfirm"]));
            }
            set {
                this["QuitConfirm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HightLightEnable {
            get {
                return ((bool)(this["HightLightEnable"]));
            }
            set {
                this["HightLightEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int FrameInterval {
            get {
                return ((int)(this["FrameInterval"]));
            }
            set {
                this["FrameInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoadFileEnable {
            get {
                return ((bool)(this["LoadFileEnable"]));
            }
            set {
                this["LoadFileEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CommentEnable {
            get {
                return ((bool)(this["CommentEnable"]));
            }
            set {
                this["CommentEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("248, 248, 242")]
        public global::System.Drawing.Color ReceBackColor2 {
            get {
                return ((global::System.Drawing.Color)(this["ReceBackColor2"]));
            }
            set {
                this["ReceBackColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("39, 40, 34")]
        public global::System.Drawing.Color ReceForeColor2 {
            get {
                return ((global::System.Drawing.Color)(this["ReceForeColor2"]));
            }
            set {
                this["ReceForeColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("248, 248, 242")]
        public global::System.Drawing.Color SendBackColor2 {
            get {
                return ((global::System.Drawing.Color)(this["SendBackColor2"]));
            }
            set {
                this["SendBackColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("39, 40, 34")]
        public global::System.Drawing.Color SendForeColor2 {
            get {
                return ((global::System.Drawing.Color)(this["SendForeColor2"]));
            }
            set {
                this["SendForeColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas, 10.5pt")]
        public global::System.Drawing.Font ReceFont2 {
            get {
                return ((global::System.Drawing.Font)(this["ReceFont2"]));
            }
            set {
                this["ReceFont2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas, 10.5pt")]
        public global::System.Drawing.Font SendFont2 {
            get {
                return ((global::System.Drawing.Font)(this["SendFont2"]));
            }
            set {
                this["SendFont2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayPlan1Enable {
            get {
                return ((bool)(this["DisplayPlan1Enable"]));
            }
            set {
                this["DisplayPlan1Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendDisplayEnable {
            get {
                return ((bool)(this["SendDisplayEnable"]));
            }
            set {
                this["SendDisplayEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ReceSendRate {
            get {
                return ((decimal)(this["ReceSendRate"]));
            }
            set {
                this["ReceSendRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkTimeNewLine {
            get {
                return ((bool)(this["chkTimeNewLine"]));
            }
            set {
                this["chkTimeNewLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"([^A-Za-z_&-]((bad|wrong|incorrect|improper|invalid|unsupported|bad)( file| memory)? (descriptor|alloc(ation)?|addr(ess)?|owner(ship)?|arg(ument)?|param(eter)?|setting|length|filename)|not properly|improperly|(operation |connection |authentication |access |permission )?(denied|disallowed|not allowed|refused|problem|failed|failure|not permitted)|no [A-Za-z]+( [A-Za-z]+)? found|invalid|unsupported|not supported|seg(mentation )?fault|corruption|corrupted|corrupt|overflow|underrun|not ok|unimplemented|unsuccessfull|not implemented|permerrors?|fehlers?|errore|errors?|erreurs?|fejl|virhe|grea|erro|fel|\(ee\)|\(ni\))[^A-Za-z_-])")]
        public string HighLightRed {
            get {
                return ((string)(this["HighLightRed"]));
            }
            set {
                this["HighLightRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("([^A-Za-z_&-](ok|accepted|allowed|enabled|connected|erfolgreich|exitoso|successo|" +
            "sucedido|successfully|successful|succeeded|success)[^A-Za-z_-])")]
        public string HighLightGreen {
            get {
                return ((string)(this["HighLightGreen"]));
            }
            set {
                this["HighLightGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[^A-Za-z_&-](\[\-w[A-Za-z-]+\]|caught signal [0-9]+|cannot|(connection (to (remote host|[a-z0-9.]+) )?)?(closed|terminated|stopped|not responding)|exited|no more [A-Za-z] available|unexpected|(command |binary |file )?not found|(o)+ps|out of (space|memory)|low (memory|disk)|unknown|disabled|disconnected|deprecated|refused|disconnect(ion)?|advertencia|avvertimento|attention|warnings?|achtung|exclamation|alerts?|warnungs?|advarsel|pedwarn|aviso|varoitus|upozorenje|peringatan|uyari|varning|avertissement|\(ww\)|\(\?\?\)|could not|unable to)[^A-Za-z_-]")]
        public string HighLightYellow {
            get {
                return ((string)(this["HighLightYellow"]));
            }
            set {
                this["HighLightYellow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[^A-Za-z_&-](debug|test)[^A-Za-z_-]")]
        public string HighLightBlue {
            get {
                return ((string)(this["HighLightBlue"]));
            }
            set {
                this["HighLightBlue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[^0-9A-Za-z_&-](localhost|([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-4])\\.[0-" +
            "9]+\\.[0-9]+\\.[0-9]+|null|none)[^0-9A-Za-z_-]")]
        public string HighLightMagenta {
            get {
                return ((string)(this["HighLightMagenta"]));
            }
            set {
                this["HighLightMagenta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[^A-Za-z_&-](last (failed )?login:|launching|checking|loading|creating|building|i" +
            "mportant|booting|starting|notice|informational|informationen|informazioni|inform" +
            "action|oplysninger|informations?|info|informaction|informasi|note|\\(ii\\)|\\(\\!\\!\\" +
            "))[^A-Za-z_-]")]
        public string HighLightCyan {
            get {
                return ((string)(this["HighLightCyan"]));
            }
            set {
                this["HighLightCyan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("([0-1][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9]):([0-9][0-9][0-9]-(<|>))")]
        public string HighLightOrange {
            get {
                return ((string)(this["HighLightOrange"]));
            }
            set {
                this["HighLightOrange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Send2FileEnable {
            get {
                return ((bool)(this["Send2FileEnable"]));
            }
            set {
                this["Send2FileEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Send2NewLineEnable {
            get {
                return ((bool)(this["Send2NewLineEnable"]));
            }
            set {
                this["Send2NewLineEnable"] = value;
            }
        }
    }
}
